training:
  epochs: 100
  seed: 2026

checkpoint:
  save_top_k: 1
  monitor: 'val_acc_avg'
  mode: 'max'
  filename: "{epoch:02d}-{val_acc_avg:.4f}-{val_loss:.4f}"

dataset: 
  class_reference: data.yfcc.TorchSpatialYfccDataset
  params:
    groupby_field: "urban_class"
    return_image_preds: False

data_loader:
  batch_size: 2048
  train_split: "train"
  val_split: "val"
  test_split: "test"

grouper:
  class_reference: wilds.common.grouper.CombinatorialGrouper
  params:
    groupby_fields: ["urban_class"]

model:
  class_reference: models.lightning.torchspatial.TorchSpatialClassification
  params:
    loc_encoder: "none"
    freeze_loc_encoder: true
    use_loc_encoder_as_prior: false
    domain_predictor_weight: 0.0
    multihead: false
    d3g_beta: 0.0
    d3g_loss_coeff: 0.0
    coral_weight: 0
    irm_weight: 0
    lr_init: 0.0001
    weight_decay: 0.0
    dropout: 0.0
    use_film: false
    film_penalty: 0
    film_lambda: 0
    n_grad_accumulation: 1
    group_wise_logging: true
    lr_scheduler:
      class_reference: torch.optim.lr_scheduler.StepLR
      params:
        step_size: 1
        gamma: 0.96
